import Link from "next/link"
import '../src/globals.css';
import Nav from "/componentes/Nav"
import {Mada} from "@next/font/google"

const fuente = Mada({
  weight: "400", 
  subsets:["latin"]
})

export const metadata = {
    title: 'Next the best FrameWork',
    description: 'Generated by Next.js',
}

export default function Rootlayout({children}) {
  return (
    <html>
        <body>
          <Nav />
          <div className={fuente.className}>{children}</div>
        </body>
    </html>
  )
}
